# Generated by Django 4.2.28 on 2026-03-27 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("social_protection", "0022_historicalproject_allows_multiple_enrollments_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("location", "0019_alter_location_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(blank=True, default="", max_length=20)),
                ("name", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANIFIE", "Planifie"),
                            ("BUDGETISE", "Budgetise"),
                            ("EN_COURS", "En cours"),
                            ("REALISE", "Realise"),
                            ("CLOTURE", "Cloture"),
                        ],
                        default="PLANIFIE",
                        max_length=20,
                    ),
                ),
                ("indicator_description", models.TextField(blank=True, default="")),
                ("province", models.CharField(blank=True, default="", max_length=255)),
                (
                    "implementing_structure",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "procurement_method",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                ("closed_date", models.DateTimeField(blank=True, null=True)),
                ("observations", models.TextField(blank=True, default="")),
                ("sort_order", models.IntegerField(default=0)),
                ("json_ext", models.JSONField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activites",
                        to="location.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activite",
                "verbose_name_plural": "Activites",
                "ordering": ["sous_composante", "sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="Composante",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=500)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Composante",
                "verbose_name_plural": "Composantes",
                "ordering": ["ptba", "sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="FundingSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Source de Financement",
                "verbose_name_plural": "Sources de Financement",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="SousActivite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(blank=True, default="", max_length=20)),
                ("name", models.CharField(max_length=500)),
                (
                    "expense_category_code",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "expense_category",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("unit", models.CharField(blank=True, default="", max_length=100)),
                (
                    "quantity_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "quantity_t1",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "quantity_t2",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "quantity_t3",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "quantity_t4",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "budget_t1",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "budget_t2",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "budget_t3",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "budget_t4",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "budget_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("json_ext", models.JSONField(blank=True, null=True)),
                (
                    "activite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sous_activites",
                        to="activity.activite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sous-Activite",
                "verbose_name_plural": "Sous-Activites",
                "ordering": ["activite", "sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="SousComposante",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=500)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "composante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sous_composantes",
                        to="activity.composante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sous-Composante",
                "verbose_name_plural": "Sous-Composantes",
                "ordering": ["composante", "sort_order", "code"],
                "unique_together": {("composante", "code")},
            },
        ),
        migrations.CreateModel(
            name="PTBA",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("fiscal_year_start", models.DateField()),
                ("fiscal_year_end", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("APPROVED", "Approuve"),
                            ("ACTIVE", "Actif"),
                            ("CLOSED", "Cloture"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("json_ext", models.JSONField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "benefit_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ptbas",
                        to="social_protection.benefitplan",
                    ),
                ),
                (
                    "user_created",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_updated",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PTBA",
                "verbose_name_plural": "PTBAs",
                "ordering": ["-fiscal_year_start"],
            },
        ),
        migrations.AddField(
            model_name="composante",
            name="ptba",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="composantes",
                to="activity.ptba",
            ),
        ),
        migrations.CreateModel(
            name="ActivityStatusTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("from_status", models.CharField(max_length=20)),
                ("to_status", models.CharField(max_length=20)),
                ("transitioned_at", models.DateTimeField(auto_now_add=True)),
                ("comment", models.TextField(blank=True, default="")),
                (
                    "activite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="activity.activite",
                    ),
                ),
                (
                    "transitioned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transition de Statut",
                "verbose_name_plural": "Transitions de Statut",
                "ordering": ["-transitioned_at"],
            },
        ),
        migrations.AddField(
            model_name="activite",
            name="sous_composante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activites",
                to="activity.souscomposante",
            ),
        ),
        migrations.CreateModel(
            name="SousActiviteFunding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "funding_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="activity.fundingsource",
                    ),
                ),
                (
                    "sous_activite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_allocations",
                        to="activity.sousactivite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allocation de Financement",
                "verbose_name_plural": "Allocations de Financement",
                "unique_together": {("sous_activite", "funding_source")},
            },
        ),
        migrations.CreateModel(
            name="QuarterlyExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quarter",
                    models.IntegerField(
                        choices=[(1, "T1"), (2, "T2"), (3, "T3"), (4, "T4")]
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "budget_prevu",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "budget_engage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "budget_decaisse",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "resultats_attendus",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "resultats_realises",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "taux_engagement",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "taux_decaissement",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "taux_realisation",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("observations", models.TextField(blank=True, default="")),
                ("reported_date", models.DateTimeField(blank=True, null=True)),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sous_activite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="activity.sousactivite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Execution Trimestrielle",
                "verbose_name_plural": "Executions Trimestrielles",
                "ordering": ["sous_activite", "year", "quarter"],
                "unique_together": {("sous_activite", "quarter", "year")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="composante",
            unique_together={("ptba", "code")},
        ),
    ]
