# Generated by Django 4.2.28 on 2026-03-27 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("activity", "0002_activite_indicators"),
    ]

    operations = [
        migrations.AddField(
            model_name="activite",
            name="revision_comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="activite",
            name="revision_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INITIAL", "Initial"),
                    ("REVISE", "Revise"),
                    ("AJOUTE", "Ajoute"),
                    ("ABANDONNE", "Abandonne"),
                ],
                default="INITIAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sousactivite",
            name="budget_initial",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="sousactivite",
            name="budget_revised",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="sousactivite",
            name="date_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sousactivite",
            name="date_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sousactivite",
            name="intervenants",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="sousactivite",
            name="quantity_initial",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="sousactivite",
            name="quantity_revised",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="sousactivite",
            name="responsible",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="sousactivite",
            name="revision_comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="sousactivite",
            name="revision_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INITIAL", "Initial"),
                    ("REVISE", "Revise"),
                    ("AJOUTE", "Ajoute"),
                    ("ABANDONNE", "Abandonne"),
                ],
                default="INITIAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sousactivite",
            name="unit_cost_initial",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="sousactivite",
            name="unit_cost_revised",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="sousactivitefunding",
            name="amount_initial",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="sousactivitefunding",
            name="amount_revised",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.CreateModel(
            name="WeeklyPlanEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("week_start", models.DateField()),
                ("week_end", models.DateField()),
                ("planned_description", models.TextField(blank=True, default="")),
                ("status_description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANIFIE", "Planifie"),
                            ("EN_COURS", "En cours"),
                            ("REALISE", "Realise"),
                            ("REPORTE", "Reporte"),
                            ("SUSPENDU", "Suspendu"),
                            ("PARTIELLEMENT_REALISE", "Partiellement realise"),
                        ],
                        default="PLANIFIE",
                        max_length=30,
                    ),
                ),
                (
                    "responsible",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "intervenants",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sous_activite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_entries",
                        to="activity.sousactivite",
                    ),
                ),
            ],
            options={
                "ordering": ["-week_start"],
                "unique_together": {("sous_activite", "week_start")},
            },
        ),
    ]
