# Generated by Django 4.2.28 on 2026-03-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "activity",
            "0003_activite_revision_comment_activite_revision_status_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklyplanentry",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
