# Generated by Django 4.2.28 on 2026-03-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0004_weeklyplanentry_date_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="sousactivite",
            name="source",
            field=models.CharField(
                choices=[
                    ("PTBA", "PTBA"),
                    ("WEEKLY", "Planification hebdomadaire"),
                    ("MANUAL", "Saisie manuelle"),
                ],
                default="PTBA",
                max_length=10,
            ),
        ),
    ]
